"""store rules and listing extraction

Revision ID: d2b728ac005a
Revises: 47edd60f524c
Create Date: 2026-10-07 09:53:38.924400

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2b728ac005a"
down_revision: str | Sequence[str] | None = "47edd60f524c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_rules",
        sa.Column("host", sa.String(length=100), nullable=False),
        sa.Column("price_selector", sa.Text(), nullable=False),
        sa.Column("availability_selector", sa.Text(), nullable=True),
        sa.Column("availability_mode", sa.String(length=10), server_default="text", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("host"),
    )
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "extraction_method",
                sa.String(length=20),
                server_default="structured",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("check_interval_minutes", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.drop_column("check_interval_minutes")
        batch_op.drop_column("extraction_method")

    op.drop_table("store_rules")
    # ### end Alembic commands ###
